"""Implements a class and functions to simplify
drawing of graphs analysing token hits"""
import json
import itertools

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from user_agents import parse

class TokenToGraph:
    """Represents a single token, which usually corresponds to a csv
    file. Contains the token hits, as well as meta information
    that AnalysisGraph uses. A TokenToGraph is passed to 
    AnalysisGraph which illustrates it.
    """

    def __init__(self, title, list_of_all_tokenhits):
        self.title = title
        self.tokenhits = list_of_all_tokenhits
        self._datapoint_tuples = [] # (category, value), generated by AnalysisGraph



class AnalysisGraph:
    """ Represents a graph that should be drawn. First
    define the graph via initialization, then call the draw() method with
    a list of tokenhits.
    The extraction_algorithm is a lambda function that returns whatever it is
    we want to group our hits by for graphing/analysis.
    For graphs that show something over time pass in over_time=True,
    this will automatically change graphing types and and show tokenhits
    relative to each other
    sort_function is usually the same as extraction_algorithm, but since
    internally we use a unix uniq-style function this needs to create an order
    that is equivalent (or at least compatible) with the extraction_algorithm)"""

    def __init__(self, graph_name, extraction_algorithm, over_time=False, sort_function=None):
        # TODO accept multiple graphs, as list
        # TODO update function doc
        self.graph_name = graph_name
        self.extraction_algorithm = extraction_algorithm
        self.over_time=over_time

        if sort_function is None:
            sort_function = extraction_algorithm
        self.sort_function = sort_function


    def draw(self, list_of_TokenToGraphs):
        """Draws this AnalysisGraph and pops up the finished graph. Expects
        a list of TokenToGraphs, which contain TokenHits as defined in main.py"""
        # TODO DOCS
        sns.set_theme()
        if self.over_time:
            plot = self._draw_continuous_plot(list_of_TokenToGraphs)
        else:
            plot = self._draw_category_plot(list_of_TokenToGraphs)

        plt.xticks(rotation=45)
        plt.show()

    def _draw_continuous_plot(self, list_of_all_tokens):
        # TODO doc
        token_dataframe = self._construct_dataframe_for_seaborn(list_of_all_tokens)
        return sns.relplot(x='Category', y='Value', hue='Token name', data=token_dataframe)

    def _draw_category_plot(self, list_of_all_tokens):
        # TODO doc
        # Apply the extraction function to the list of all tokens
        token_dataframe = self._construct_dataframe_for_seaborn(list_of_all_tokens)
        return sns.catplot(x='Category', y='Value', hue='Token name', data=token_dataframe, kind='bar')


    def _construct_dataframe_for_seaborn(self, tokens_list):
        # TODO
        """ [category, token name, value],
        [category, token name, value]"""
        category_list = []
        token_name_list = []
        value_list = []

        for token in tokens_list:
            datapoints_of_token = self._get_datapoint_tuples_from_TokenToGraph(token)

            for datapoint in datapoints_of_token:
                category_list.append(datapoint[0])
                token_name_list.append(token.title)
                value_list.append(datapoint[1])

        token_dataframe = pd.DataFrame({'Category': category_list,
                'Token name': token_name_list,
                'Value': value_list})
        return token_dataframe


    def _get_datapoint_tuples_from_TokenToGraph(self, token_to_graph):
        # TODO 
        datapoint_tuples = []
        list_of_all_tokenhits = token_to_graph.tokenhits
        list_of_all_tokenhits.sort(key=self.sort_function)
        if self.over_time:
            # "buckets" for this are "this is the nth request",
            # so all buckets have size 1. This information is not contained
            # within a hit, it is relative,
            # so we run all our map functions over the hits (sorted
            # by our extraction algorithm) enriched with what their position
            datapoint_tuples = list(map(
                self.extraction_algorithm,
                list_of_all_tokenhits, range(len(list_of_all_tokenhits))))
        else:
            # Sort all hits into buckets
            for key, group in itertools.groupby(list_of_all_tokenhits, self.extraction_algorithm):
                group_size = sum(1 for _ in group)
                datapoint_tuples.append((key,group_size))

        return datapoint_tuples



def build_graphs_over_time():
    """Returns a list of all time-relative graphs
    we want to draw.
    """
    graphs_to_draw = [
            AnalysisGraph("Requests over time",
                lambda hit, position : (hit.timestamp, position),
                over_time=True,
                sort_function=lambda hit:hit.timestamp)
            ]

    return graphs_to_draw


def build_graphs_over_all():
    """Returns a list of all graphs
    we want to draw that analyse all hits by some metric
    """
    graphs_to_draw = [
            AnalysisGraph("Requests by country",
                lambda hit: json.loads(hit.geo_info)["country"]),

            AnalysisGraph("Requests by Region",
                lambda hit: json.loads(hit.geo_info)["region"]),

            AnalysisGraph("Requests by browser family",
                lambda hit: parse(hit.useragent).browser.family),

            AnalysisGraph("Requests by os",
                lambda hit: parse(hit.useragent).os.family),

            AnalysisGraph("Requests by mobile devices",
                lambda hit: "Mobile" if parse(hit.useragent).is_mobile else "PC")
            ]
    return graphs_to_draw


def run_analyses(list_of_all_tokensToGraph):
    """Draws all graphs defined in build_graphs_over_time
    and build_graphs_over_all"""
    # TODO Docs
    graphs_to_draw = []
    graphs_to_draw += build_graphs_over_time()
    graphs_to_draw += build_graphs_over_all()


    for graph in graphs_to_draw:
        graph.draw(list_of_all_tokensToGraph)
